### ISSUE TITLE
Ocean World

### ISSUE THREAD

**Issue by RagingGamerChris** [MCTCP/TerrainControl#347]
Every time I create a world, it just makes an ocean world, with no mainland. I have tried the default configuration, and that as well turns the world into an ocean. Disabling the waterlevel (setting max waterlevel to 0) will create a world with one biome, plains. After around 15 attempts of getting this to work propperly, I am starting to give up. I have followed all the instructions, as well as an hour long video on YT. Nothing seems to fix this. Please help!

**Comment by rutgerkok** [comment]
For me the seed 12 always spawns me on land - maybe that works for you?

As a test, you can also try to set LandRarity to 100 to disable oceans altogether.

**Comment by grimmeral** [comment]
I actually went into spectator mode to test this out, as it happens to me every now and then. If you are generating a Normal world with just a few biomes, TC tends to spawn more ocean in because it does not have much variety. But actually, if you travel a REALLY LONG AND BORING amount of time you will come to land at some point. There's always land, just maybe not near.

**Comment by rutgerkok** [comment]
Yeah, it's annoying that TC doens't make any effort to look for a suitable spawn location. I'm closing this ticket, as there is already another ticket open (#346) about this issue.
