### ISSUE TITLE
Changing Temperature doesn't affect anything

### ISSUE THREAD

**Issue by Masy98** [MCTCP/TerrainControl#369]
As mentioned in #366 changing the temperature doesn't affect the weather (like it should).
If i have a Taiga biome and set the temperature to 2.0 instead of 0.0 it still snows and spawns with snow. If i make a custom biome that just hast ReplaceToBiomeName set to Taiga and change the temperature to 2.0 and keep it 2.0 in the Taiga.bc it spawns without snow, but when i turn on rain it snows.

(Changed BiomeHeight to 3.92 and raised WaterLevel to 127)

**Comment by rutgerkok** [comment]
Changing the temperature of default biomes (or custom biomes that replace themselves to default biomes) won't work - the temperature and wetness of those biomes is decided by Minecraft.

For the default Taiga biome, the temperature value is completely ignored and snow spawns anyways. For a custom biome, the temperature value is honored. After terrain generation is done, the biome is replaced to Taiga, and from that moment on, snow can fall rom the sky.

**Comment by Masy98** [comment]
But when i make a custom Biome and don't type anything in the ReplaceToBiomeName Tag it automatically chooses plains and copys that grass color.

**Comment by rutgerkok** [comment]
That's what the Minecraft client displays, but on the server, the biome is there. If you use the TerrainControl client mod, you would see the biome. However, even on the vanilla client you should see snow on the ground.

As a workaround, you can replace the biome to a vanilla biome that doesn't have snow.

**Comment by Masy98** [comment]
Well that's my point. I want to make a biome with Taiga grasscolor AND no snow. the only 2 options i seem to have are either making it display as plains and have no snow but have wrong grass color OR making it display Taiga and have the right grass color but snow. And that's what my question is: is there a way around this (without the clientmod)?

**Comment by ThatSoundsFun** [comment]
I know this issue is old, but you could control the temperature in the forge version of any biomes. Why isn't this possible in the spigot version?

**Comment by rutgerkok** [comment]
You can always control the temperature of custom biomes on the server, using either Spigot or Forge. For custom biomes to show up correctly on the client, you need to patch the client. This can be done by installing the Forge version of TerrainControl on the client.

It is not possible to install the Spigot version of TerrainControl on the client. This is because Spigot has no support for modding the Minecraft client.

Alternatively, you can change the custom biome ids in the world to the ids of a vanilla biome. This only keeps the *block* ids of the custom biome, but all other biome-specific (temperature, weather, colors, mobs) things of the custom biome are lost: the temperature, weather, etc. of the replacing biome are now used.

**Comment by ThatSoundsFun** [comment]
What i meant was that you could control the temperature of vanilla biomes in the forge version, but not in the spigot version.

Here's the result of lowering the temperature of a deep ocean biome in the forge version.

Before:
![2015-12-30_16 50 07](https://cloud.githubusercontent.com/assets/13108825/12058114/6f7c739e-af16-11e5-8924-cf784661097e.png)

After:
![2015-12-30_16 52 55](https://cloud.githubusercontent.com/assets/13108825/12058120/7d49d20a-af16-11e5-9211-107ea764e09a.png)

**Comment by rutgerkok** [comment]
Hmm, interesting. Seems like in Forge you can still change the temperature of default biomes. On Bukkit this led to problems because changing the default biome in one world affects that biome in all other worlds too, but as the Forge version has no multiworld support, changing the temperature is still allowed by TC.

I can make things consistent by also dissallowing people to change the temperature in default biomes on Forge, but that probably won't make anyone happy. Also allowing people to change the temperature on the Spigot version is possible, but will unfortunately also change the biome temperature on other worlds.

**Comment by ThatSoundsFun** [comment]
Maybe an option could be added in TC where it allows you to change the temperature of vanilla biomes for one world and warns you that doing so will affect every world. The only problem i see is when two worlds have the option turned on and has a conflict with biome temperature. That case I guess it could use the vanilla temperature instead.
