### ISSUE TITLE
Surface+Ground control is inconsistent underwater

### ISSUE THREAD

**Issue by Piginabag** [MCTCP/TerrainControl#377]
I was using a version of terrain control from Nov 2014 and recently updated to 2.7.2. I was using this line in my ocean biome previously: SAND, SANDSTONE, -0.8, PRISMARINE, SANDSTONE, 0.0, SAND, SANDSTONE, 10.0

This setting still works for land based biomes but does absolutely nothing underwater in 2.7.2

**Comment by rutgerkok** [comment]
That is annoying... In TC 2.7.2 I switched to using Minecraft's way of creating alternating surfaces, instead of the hack during terrain population we had before. The new code is faster and more in line with vanilla Minecraft behaviour, but as you have found out it is not ideal.

In vanilla Minecraft (and now in TerrainControl too), underwater the surface block is skipped and the ground block is exposed. SurfaceAndGroundControl sets the ground block for the column to the second material, in your case always `SANDSTONE`. Maybe you can change that to PRISMARINE? You would then have this:

 SAND, SAND, -0.8, PRISMARINE, PRISMARINE, 0.0, SAND, SAND, 10.0

(sandstone spawns below sand automatically, so no need to add that too)

**Comment by Piginabag** [comment]
Yeah. It works as you suggested. I had no idea that the surface block is being replaced underwater; this is good to know.

**Comment by rutgerkok** [comment]
Yeah, it's probably coded that way by Mojang to prevent grass from spawning underwater.
