### ISSUE TITLE
Plains biome is set as ocean

### ISSUE THREAD

**Issue by Dhs92** [MCTCP/TerrainControl#383]
If the title doesn't make sense, then sorry. My world currently has TC enabled and I have generated some new land. Ocean Monuments are being generated in my plains area, and F3 says the biome is Deep ocean. Anyway to fix this?

http://pastebin.com/apUiSyZ7 - Config for the world

**Comment by Nicofisi** [comment]
What does /tc biome say?

**Comment by Dhs92** [comment]
Says Deep Biome, ID 24

**Comment by Nicofisi** [comment]
Can we get config for the biome? Have you changed anything?

**Comment by Dhs92** [comment]
@Nicofisi I have not changed anything in the biomes folder

**Comment by rutgerkok** [comment]
Plains normally has the biome id 1, but somehow the save files now have the biome id 24. There must be a reason for this.

Are you using the default settings of TerrainControl, or have you changed things? Is the world newly generated, or has it been in use previously? Have you used some world editor for that world?

If it's a new world, you can probably just delete the world files and hope this doesn't happen again. You can also try to reset the TerrainControl settings to their defaults. (If you delete a configuration file, TerrainControl will automatically recreate it with the default settings.)

**Comment by Dhs92** [comment]
I posted my configuration file. This also happens every time I create a new world with TC

**Comment by rutgerkok** [comment]
It is difficult to see what changed from the default settings: I have to compare all values with the defaults of TerrainControl. After looking at them, I can see that the river settings and most of the biome placement settings are changed in the WorldConfig.

Based on the information that this happens every time you create a new world, we know that it is TerrainControl that is generating biomes that look like plains, but have the biome id of Deep Ocean.

That is strange. Why does a Plains biome get replaced to Deep Ocean? Why not, for example, to Savanna M? There must be a logical reason why this happens.

One thing you could to is to find out if this happens for you in the default settings. Rename the folder the WorldConfig is in, so that TerrainControl recreates everything.

If you want me to reproduce this, then you'll need to say exactly where (coords and seed) this happens.

**Comment by Dhs92** [comment]
This happens on all plains "biomes" and with every seed I have tried. I will regenerate the config and get back to you as soon as I can.

**Comment by Dhs92** [comment]
@rutgerkok Sorry to bother you, but I don't know if you saw my  updates or not.

**Comment by rutgerkok** [comment]
Found the issue.

You set WorldHeightScaleBits to 8. According to the documentation of that setting, "adding 1 to this doubles the height of the terrain". So the landmass is now double as high, but the water is still left at y=64. You can set WaterLevelMax to 128 to turn it back into an ocean.

**Comment by Dhs92** [comment]
Now everything is frozen even with the default biome settings >_>

**Comment by rutgerkok** [comment]
The biome you are in probably has a low temperature. What does `/tc biome` say?

**Comment by Dhs92** [comment]
Sorry, poor wording. I meant to say that every biome is a frozen biome. I can't seem to find a plains or desert.

**Comment by JfromHolland29** [comment]
@Dhs92 you can make a TC Map and search for other biomes, can't you?
