### ISSUE TITLE
IllegalStateException: Chunk is already being populated

### ISSUE THREAD

**Issue by bcurtiswx** [MCTCP/TerrainControl#394]
Seems insert code cuts it off, so here: http://paste.ubuntu.com/15383772/

**Comment by rutgerkok** [comment]
Thanks.

However, just from the error message, I cannot fix this. It looks like the server timed out, but the exact reason is unclear to me.

Have you changed the `timeout-time` in the spigot.yml to a lower number? If yes, please restore it to its original value. If not, please read on.

Is your world normally generated really slow? Or is it just this time that it hangs?

I'm going to need some way to reproduce this to be able to fix this. Could you give me steps so that I can see this error myself?

If this only happens with your configuration files (and not the default settings), you'll also need to send your configuration files. (If you don't want the files to be available to the general public, you can do so by email, see my Github profile for the address.) If the error only happens at a certain location in your world, I will also need the coords and world seed.

**Comment by bcurtiswx** [comment]
http://paste.ubuntu.com/15401519/

Newest crash, may be more aparrent whats happening.

Recap: timeout-time is default. World generates quite fast. If this doesn't shed some light i'll plop the config file over to you. Lemme know.

**Comment by bcurtiswx** [comment]
I didn't mean to close it, not sure why that happened.

**Comment by rutgerkok** [comment]
It seems Mojang's light code is loading a chunk while another chunk is already being loaded. This should be enough information for me to fix it, thanks.

**Comment by rutgerkok** [comment]
I have not yet been able to fix the error. However, I have created [a new build](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/default/lastBuild/) of TerrainControl that should give more information about what's going wrong: it will now report the block coords, as well as the chunk location. Would you be willing to install this build, and report the error when the server crashes again?

**Comment by bcurtiswx** [comment]
I have added it to the server. I will post here if I get any more errors/crashes.

**Comment by rutgerkok** [comment]
Thanks!

**Comment by cjburkey01** [comment]
I am also getting this error on the newer version.  It's the same crash report, the one thing I am doing is Pregening the world with WorldBorder.  Could that be causing my crash?

**Comment by rutgerkok** [comment]
@cjburkey01 

There are two different crash reports in this thread. Could you post the error?

If it's the "Chunk is already being populated" error, then a crash report would be very useful. If it's the "Server has stopped responding" error, then there's not much I can do.

**Comment by cjburkey01** [comment]
I've actually received both of them.  Both did occur only when I had the world generating with WorldBorder though.

**Comment by BlackXnt** [comment]
http://pastebin.com/2ZbVAe2C

I am getting this with version 2.8.0.

**Comment by rutgerkok** [comment]
Thank you, that crash report provides me with the source of the error.

When placing lava blocks, a block was placed at the edge of the chunk. The lava then started flowing into unloaded chunks.

I can't see any way to disable this physics update (this particular phyiscs update is wired to the code that gets executed when a lava blocks is placed), so you'll have to set `PopulationBoundsCheck` to `false` in your WorldConfig. (Vanilla Minecraft always generates stone around lava, so it doesn't have this problem.)
