### ISSUE TITLE
Generation bugs on 1.9.4

### ISSUE THREAD

**Issue by Bayside308** [MCTCP/TerrainControl#430]
I'm currently running the latest version of 1.9.4, and the terrain generation is going to all hell. Each chunk is generating independently of the others around it, and a regen creates massive mountains.

I'm downgrading to 1.9.2 because I believe it worked then.

Running TerrainControl on the overworld only and using the BBundle pack

I hope you can fix this!

![terraincontrol](https://cloud.githubusercontent.com/assets/16769193/15451283/d177d0b0-1f88-11e6-9efa-87ce015d695a.png)

http://prntscr.com/b6vdqk

**Comment by rutgerkok** [comment]
Based on just this screenshot, the bug could be caused by a lot of things: TerrainControl crashing, the level.dat being corrupted, etc.

I need some way to reproduce this issue. So I need exact steps that I can follow, so that I will also see this bug. As long as it doesn't happen on my computer, I cannot fix it. What is probably needed:

* the world seed
* the TerrainControl configuration files used ("Biome Bundle" has many versions, which are incompatible which each other)
* The TerrainControl build that you used
* The Spigot/Paper/whatever version that you used

This should be enough for me to reproduce the issue.

**Comment by aycgit** [comment]
is it true that this happened after a crash and tc isnt enabled anymore in the world?
