### ISSUE TITLE
Structure generation and CustomObject duplication

### ISSUE THREAD

**Issue by eccentricdevotion** [MCTCP/TerrainControl#431]
I'm having an issue with village structure generation in a custom TerrainControl world. Village buildings are doubling up e.g.:

![Double height village](https://dl.dropboxusercontent.com/u/53758864/doubleheightvillage.jpg)

Also noticed some odd behaviour when adding CustomObjects, which I managed to fix by doing a  `BlockCheck(0,-1,0,SAND,HARD_CLAY)`

![Duplicate TARDII](https://dl.dropboxusercontent.com/u/53758864/skaro_tardises.jpg)

Have only edited the WorldConfig.ini which can be seen here: [http://pastebin.com/RQWBVnAm](http://pastebin.com/RQWBVnAm)

police_box.bo3 is here: [http://pastebin.com/3kNtj4mB](http://pastebin.com/3kNtj4mB])

CraftBukkit version git-Bukkit-d8637df (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
TerrainControl v2.8.1-SNAPSHOT build 142

**Comment by rutgerkok** [comment]
The first is because how Minecraft generates villages - it always spawns them above sea level, never below. You can change the sea level by chaning WaterLevelMax in the WorldConfig. It's weird vanilla behaviour. You'll find out that ocean monoments have the same issue.

The second issue is just how BO3s work - if you don't define what a suitable location is, every location is considered a suitable location, including on top of other BO3s.

**Comment by eccentricdevotion** [comment]
Thanks for clarifying.

As a new user of TerrainControl, the behaviour was a little unexpected. Perhaps the default WorldConfig should have a WaterLevelMax setting that mimics the vanilla Minecraft values, so that noobs like me don't freak out and make unneeded issues :)

**Comment by rutgerkok** [comment]
The default WaterLevelMax is 63 - this is already the default of vanilla Minecraft.
