### ISSUE TITLE
Mojang created structures spawning everywhere

### ISSUE THREAD

**Issue by Robanaan** [MCTCP/TerrainControl#440]
Hello. 

The default minecraft structures (Like village, temple, igloo and even surface mineshaft and oceantemple etc.) are spawning in biomes where they are not supposed to and also when they are not supposed to in the #154 Build. The objects spawned in biomes even though my configs said they should not spawn. I also had noticed this in the #150 build but I had solved this issue by just removing the CustomObject(UseWorld) from every biomeconfig.

Here are some pictures of what I mean (Left is #154, Right #150):
(Note: I only let the biomes spawn structures like vanilla minecraft would. CustomObject(UseWorld) is also removed!)
http://imgur.com/a/qv9Gl

The Surfaceshafts (which should only spawn in the Mesa) however, are a problem in both versions:
http://imgur.com/BkDfXaf

Hope this helps.

EDIT: Example config: http://pastebin.com/zPfpGPuN

**Comment by Robanaan** [comment]
I looked around through the commits and the villages and temples probably have to do with this one:
https://github.com/MCTCP/TerrainControl/commit/c85d73d680633867c83f4c8e424334a6bfdfe5fc 
I have no experience with java so I don't know what is wrong myself. I don't know about the surface mineshafts though, since they were broken before that commit.

**Comment by rutgerkok** [comment]
I cannot reproduce this. As a first test, I set the amount of villages in the WorldConfig to a really high value, so that there are villages everywhere in the plains biome. However, in the roofed forest biome, there are as expected no villages:

![image](https://cloud.githubusercontent.com/assets/1462188/16766482/c40345b0-483a-11e6-8ac6-371ebd7c29f4.png)

Then I created a world with your biome config, again I saw no strange structures:

![image](https://cloud.githubusercontent.com/assets/1462188/16766735/1ef47d3a-483c-11e6-8b39-65524877ea4f.png)

Could you create a ZIP file with the configs that reproduce this problem?

**Comment by Robanaan** [comment]
Okay, for some reason I'm not even able to reproduce this problem myself. Even though I was able to yesterday. The villages and temple are no longer there and I couldn't find them anywhere else either. 

The surface/mesa mineshafts are still there though

Here are the configs:
https://www.dropbox.com/s/agaj80mrj09u30b/TerrainControl.zip?dl=0
(for some reason it wouldn't let me upload a zip file to this comment.)

The seed is -1747477043061145549
you can find a mineshaft at the coordinates in the picture which I showed earlier.

**Comment by rutgerkok** [comment]
[Build 156](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/156/default/) should fix this.
