### ISSUE TITLE
Branches spawn even if previous branches failed to spawn

### ISSUE THREAD

**Issue by Masy** [MCTCP/TerrainControl#459]
This leeds to weird behaviour like in my case:
![2016-09-15_18 54 16](https://cloud.githubusercontent.com/assets/7923485/18596469/8bcaf5e2-7c49-11e6-99ed-85cc547ae0d9.png)

I wrote a path generator wich first randomly generates a well which then generates paths so that every village has exactly one well. On the picture you can see that it tried to spawn the well, but it failed because of my BlockChecks, the paths still got generated though...

**Comment by fatboy2380** [comment]
I can also confirm I have experienced this issue, specifically when using multiple options for a branch, it continues to branch out even if a bo3 is selected without any more branches

**Comment by rutgerkok** [comment]
This is, unfortunately, intended behaviour. Terrain generation works on a single chunk in Minecraft. The terrain generator decided to spawn a village somewhere, and generated some paths. Once the chunk containing the center piece with the well was generated, the server noticed that the terrain wasn't suitable for a well after all. But at that point the paths were already generated...

This is why Minecraft villages spawn no matter what, even if the terrain turns out to be unfavourable.
