### ISSUE TITLE
TerrainControl producing error with Multiverse-Core

### ISSUE THREAD

**Issue by NerdyBirder** [MCTCP/TerrainControl#551]
I use multiverse to create multiple worlds on the spigot server that I help run. When trying to run different generators through multiverse we have had some success with other generators but can not seem to get TerrainControl to work. The plugin has loaded successfully but when typing the command /mv gens it brings up an error:

2:47:11 PM Multiverse-Core: PLEASE IGNORE the 'Plugin X does not contain any generators' message below!

**Comment by bloodmc** [comment]
You need to provide more information. What versions are you using? Include complete server log and exact steps used to reproduce the issue.

**Comment by NerdyBirder** [comment]
We have decided not to pursue this plugin anymore since it is not updated to 1.12. Our server is running on 1.12.2 and that is probably the source problem with the plugin not working on with multiverse on our end.

**Comment by bloodmc** [comment]
Uh what? TerrainControl was updated to 1.12.2 which is why I specifically asked you what versions you were running.

I went ahead and tested the latest MV with TC myself and had 0 issues. Here is the output from running /mv 

[13:44:38 INFO]: [Multiverse-Core] PLEASE IGNORE the 'Plugin X does not contain any generators' message below!
[13:44:38 INFO]: [TerrainControl] Starting to enable world ''world''...
[13:44:38 INFO]: [TerrainControl] 0 world custom objects loaded.
[13:44:39 INFO]: [TerrainControl] 62 biomes Loaded
[13:44:39 INFO]: --- Loaded Generator Plugins ---
[13:44:39 INFO]: TerrainControl

Also the error literally states in caps "PLEASE IGNORE" which is NOT an error and is always logged as shown in source here

https://github.com/Multiverse/Multiverse-Core/blob/master/src/main/java/com/onarandombox/MultiverseCore/commands/GeneratorCommand.java#L40

**Comment by NerdyBirder** [comment]
Ok thank you for the information. I do think that the problem is on our side and that is part of the reason that I closed this issue card. I will need to investigate it further to see what might be causing the issue on my server.

**Comment by bloodmc** [comment]
Make sure you are using the latest build

http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/default/lastStableBuild/artifact/platforms/bukkit/build/distributions/terraincontrol-bukkit-2.8.3-SNAPSHOT.jar
